name: build the thingamabobby

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cc: gcc
            calc_out: calculator-linux
            wc_out: wordcounter-linux

          - os: macos-latest
            cc: clang
            calc_out: calculator-macos
            wc_out: wordcounter-macos

          - os: windows-latest
            cc: gcc
            calc_out: calculator.exe
            wc_out: wordcounter.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MinGW
        if: matrix.os == 'windows-latest'
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Build programs
        run: |
          ${{ matrix.cc }} calculator.c -o ${{ matrix.calc_out }}
          ${{ matrix.cc }} wordcounter.c -o ${{ matrix.wc_out }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: |
            ${{ matrix.calc_out }}
            ${{ matrix.wc_out }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
